stages:
  - test
  - build

.go-cache: &go-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go/pkg/mod/
    policy: pull-push

include:
  - project: 'coldforge/ci-templates'
    ref: main
    file: '/templates/cloistr-rules.yml'
  - project: 'coldforge/ci-templates'
    ref: main
    file: '/templates/go-test.yml'
  - project: 'coldforge/ci-templates'
    ref: main
    file: '/templates/kaniko-build.yml'



build:
  extends: .kaniko-build
  stage: build

test:unit:
  extends: [.go-test, .cloistr-rules]
  variables:
    GO_TEST_DIR: "backend"

lint:
  extends: [.go-lint, .cloistr-rules]
  variables:
    GO_TEST_DIR: "backend"
