apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: coldforge-vault
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "vault_db"
  DB_USER: "vault_user"
  DB_SSLMODE: "require"
  PORT: "8080"
  HOST: "0.0.0.0"
  ENVIRONMENT: "production"
  SCRYPT_N: "32768"
  SCRYPT_R: "8"
  SCRYPT_P: "1"
  SESSION_DURATION_HOURS: "24"