apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: coldforge-vault
type: Opaque
data:
  DB_PASSWORD: M3U2Y2NDZHF3Rm94ZzlpdTNQTDV0c1BJWlRRcnNVcg==
  JWT_SECRET: YTJ5OGEzaGphdTc4ZzJDa3VUdDk5ZWZTQUljNlA3NUFBQU5SWk5YdERXcHh3cG1kTlM1eFd4RUJDRVhRWWxs
  
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: coldforge-vault
type: Opaque
data:
  POSTGRES_USER: dmF1bHRfdXNlcg==
  POSTGRES_PASSWORD: M3U2Y2NDZHF3Rm94ZzlpdTNQTDV0c1BJWlRRcnNVcg==
  POSTGRES_DB: dmF1bHRfZGI=